apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke-upgrade-sles
  namespace: rke-upgrade-sles
spec:
  concurrency: 1
  tolerations:
  - {key: CriticalAddonsOnly, operator: Exists}
  nodeSelector:
    matchExpressions:
    - {key: skip-rke-upgrade-sles, operator: DoesNotExist}
  serviceAccountName: rke-upgrade-sles
  drain:
    force: false
  version: sles15sp6-20240704
  secrets:
    - name: rke-upgrade-sles-script
      path: /host/run/system-upgrade/secrets/upgrade
  upgrade:
    image: registry01.suse/rke-prod/spacecmd:15.6.1
    command: ["bash", "/host/run/system-upgrade/secrets/upgrade/start.sh"]
